Repository Spaghetti-coding-club/JangGaeJaRang, pull requests merged in 2022-08, with the labels that each got.

#4 Add mainbutton component
  App/Sources/Presentation/Components/Components.swift
  App/Sources/Presentation/Components/MainButtonComponent.swift
  App/Sources/Presentation/Components/MainButtonStyle.swift
Labels: ✨ Feature, ⚙ Setting

#8 🔀 :: 6 signin feature setup
  App/Project.swift
  App/Sources/Presentation/Scenes/Signin/SigninVM.swift
  App/Sources/Presentation/Scenes/Signin/SigninView.swift
  App/Sources/Presentation/Utils/Base/BaseViewModel.swift
  App/Support/JangGaeJaRang.entitlements
  Tuist/ProjectDescriptionHelpers/Project+Template.swift
Labels: ⚙ Setting, 0️⃣Priority: Critical

#10 Add feature MainButton component
  App/Sources/Presentation/Components/MainButtonComponent.swift
  App/Sources/Presentation/Components/MainButtonStyle.swift
Labels: ✨ Feature

#20 13 create signup view step2
  App/Sources/Presentation/Components/SelectableButtonComponent.swift
  App/Sources/Presentation/Scenes/Signup/SignupStep2VM.swift
  App/Sources/Presentation/Scenes/Signup/SignupStep2View.swift
Labels: ✨ Feature

#22 feat: signupStep present 구현
  App/Derived/Sources/TuistAssets+JangGaeJaRang.swift
  App/Sources/Presentation/Scenes/Signup/SignupStep1View.swift
  App/Sources/Presentation/Scenes/Signup/SignupStep2View.swift
Labels: ✨ Feature, 0️⃣Priority: Critical
